[project]
name = "resume-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sanemi07", email = "arjuntripathi1724@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "groq>=1.7.0",
    "pydantic>=2.13.5",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.4",
]

[project.scripts]
resume-parser = "resume_parser:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
